name: Run account-service Collection

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  postman:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Postman CLI
        run: curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh

      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}

      - name: Run collection
        run: postman collection run "postman/collections/account-service" -e "postman/environments/Accounts TEST.environment.yaml" --report-events
